services:
  redis:
    image: redis:alpine

  trainer:
    build:
      context: .
      dockerfile: docker/Dockerfile  # Points to the actual location
    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data
    # Use the full module path to the script
    command: python -m app.train_models.train_each_model

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts
      - shared_results:/shared/results
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_started
      trainer:
        condition: service_completed_successfully
    command: uvicorn app.api.api:app --host 0.0.0.0 --port 8000

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A app.api.worker.celery_app worker --loglevel=info
    volumes:
      - ./artifacts:/app/artifacts
      - shared_results:/shared/results
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_started
      trainer:
        condition: service_completed_successfully

volumes:
  shared_results: